import * as fs from 'fs';
import svelte from 'rollup-plugin-svelte';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import buble from 'rollup-plugin-buble';
import uglify from 'rollup-plugin-uglify';
import CleanCSS from 'clean-css';

const production = !!process.env.production;

export default {
  entry: 'src/main.js',
  dest: 'public/bundle.js',
  format: 'iife',
  moduleName: 'app',
  sourceMap: true,
  plugins: [
    svelte({
      css ( css ) {
        if ( css === null ) css = '';
        if ( production ) css = new CleanCSS().minify( css ).styles;
        fs.writeFileSync(
          'public/app.css',
          `/* This file is automatically generated — don't edit it! */\n${css}`
        );
      }
    }),
    resolve(),
    commonjs(),
    production && buble({ exclude: 'node_modules/**' }),
    production && uglify()
  ]
};